<?php

/**
 * @file
 * Contains custom_gen.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_gen_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_gen module.
    case 'help.page.custom_gen':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom General') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_gen_theme() {
  return [
    'custom_gen' => [
      'render element' => 'children',
    ],
  ];
}
